In [0]:
import pandas as pd

In [0]:
df_oceans = pd.read_csv('dados_oceans14.csv', encoding='utf-8')
df_oceans = df_oceans[df_oceans['ano'] == 2020]
df_oceans.set_index('tick', inplace=True)
df_bruto_status = pd.read_csv('dados_brutos_status_invest-2020_06_15.csv', encoding='utf-8', sep=';')

In [28]:
df_oceans.columns

Index(['ano', 'divida_liq_EBITDA', 'ROIC', 'VPA', 'ROA', 'P_L', 'PSR', 'P_VP',
       'ECP', 'P_EBIT', 'DY', 'ROE', 'P_ativos', 'margem_EBITDA', 'LPA',
       'margem_liq', 'EV_EBITDA', 'beta', 'P_EBITDA', 'EV_EBIT'],
      dtype='object')

In [29]:
df_bruto_status.columns

Index(['TICKER', 'PRECO', 'DY', 'P/L', 'P/VP', 'P/ATIVOS', 'MARGEM BRUTA',
       'MARGEM EBIT', 'MARG. LIQUIDA', 'P/EBIT', 'EV/EBIT',
       'DIVIDA LIQUIDA / EBIT', 'DIV. LIQ. / PATRI.', 'PSR', 'P/CAP. GIRO',
       'P. AT CIR. LIQ.', 'LIQ. CORRENTE', 'ROE', 'ROA', 'ROIC',
       'PATRIMONIO / ATIVOS', 'PASSIVOS / ATIVOS', 'GIRO ATIVOS',
       'CAGR RECEITAS 5 ANOS', 'CAGR LUCROS 5 ANOS', ' LIQUIDEZ MEDIA DIARIA'],
      dtype='object')

In [0]:
COLUNAS_UTILIZADAS = ['TICKER', 'DY', 'P/L', 'P/VP', 'P/ATIVOS', 'MARGEM EBIT', 'MARG. LIQUIDA', 'P/EBIT', 'EV/EBIT', 'DIVIDA LIQUIDA / EBIT', 'PSR', 'LIQ. CORRENTE', 'ROE', 'ROA', 'ROIC', 'CAGR LUCROS 5 ANOS', ' LIQUIDEZ MEDIA DIARIA']
COLUNAS_UTILIZADAS_AJEITADAS = ['tick', 'DY', 'P_L', 'P_VP', 'P_ativos', 'margem_EBIT', 'margem_liq', 'P_EBIT', 'EV_EBIT', 'divida_liq_EBIT', 'PSR', 'liq_corrente', 'ROE', 'ROA', 'ROIC', 'lucros_5anos', 'liq_media_diaria']

In [43]:
df_status = df_bruto_status[COLUNAS_UTILIZADAS].copy()
df_status.columns = COLUNAS_UTILIZADAS_AJEITADAS
df_status.set_index('tick', inplace=True)
df_status

          DY    P_L   P_VP  ...   ROIC lucros_5anos liq_media_diaria
tick                        ...
AALR3   0,80  69,45   0,99  ...   4,36          NaN     9.190.647,37
ABCB4   7,12   6,57   0,80  ...    NaN         8,66    12.310.552,40
ABEV3   3,64  19,89   2,94  ...  19,35        -0,28   395.449.207,87
ADHM3    NaN  -3,03  -0,95  ...  22,61          NaN       192.560,50
AFLT3   1,06  25,38   2,85  ...  10,08        11,01        78.720,17
...      ...    ...    ...  ...    ...          ...              ...
WIZS3   5,99   8,18   7,19  ...  92,92        21,33    11.146.933,30
WLMM3   2,79   7,94   0,97  ...  11,33        32,46         5.219,13
WLMM4   2,21  11,03   1,35  ...  11,33        32,46        23.438,70
WSON33  3,86  33,60   0,92  ...   4,04         4,05     1.756.442,03
YDUQ3   1,55  17,69   3,10  ...  12,43        12,26   128.947.298,83

[525 rows x 16 columns]

In [33]:
df_oceans

         ano  divida_liq_EBITDA  ROIC  ...  beta  P_EBITDA  EV_EBIT
tick                                   ...
AALR3   2020               2.53  0.05  ...  0.77      4.59    15.04
ABEV3   2020               0.00  0.18  ...  0.62      9.43    11.79
ALPA4   2020               0.00  0.08  ...  0.97     42.15    53.03
ALSO3   2020               0.00  0.04  ...  1.19     13.84    16.18
ALUP11  2020               1.82  0.16  ...  0.55      2.78     4.81
...      ...                ...   ...  ...   ...       ...      ...
VVAR3   2020               0.00 -0.06  ...  1.56   -293.59   -17.01
WEGE3   2020               0.00  0.15  ...  0.87     32.54    39.07
WIZS3   2020               0.00  0.72  ...  0.86      0.00     3.07
WSON33  2020               3.88  0.06  ...  0.61      4.19    14.15
YDUQ3   2020               0.78  0.17  ...  1.05      6.87    10.88

[165 rows x 20 columns]

In [45]:
colunas_exclusivas_oceans = list(set(df_oceans.columns) - set(COLUNAS_UTILIZADAS_AJEITADAS))
df_oceans = df_oceans[colunas_exclusivas_oceans]
df_oceans

         ECP  beta    VPA  divida_liq_EBITDA  ...   LPA   ano  P_EBITDA  EV_EBITDA
tick                                          ...
AALR3   0.56  0.77  10.96               2.53  ...  0.16  2020      4.59       7.12
ABEV3   0.22  0.62   4.58               0.00  ...  0.68  2020      9.43       8.93
ALPA4   0.82  0.97   4.87               0.00  ...  0.41  2020     42.15      41.29
ALSO3   0.00  1.19  28.67               0.00  ...  0.48  2020     13.84      10.96
ALUP11  0.10  0.55  25.73               1.82  ...  5.61  2020      2.78       4.60
...      ...   ...    ...                ...  ...   ...   ...       ...        ...
VVAR3   0.84  1.56   0.49               0.00  ... -1.06  2020   -293.59    -378.73
WEGE3   0.35  0.87   4.71               0.00  ...  0.85  2020     32.54      32.36
WIZS3   0.00  0.86   1.55               0.00  ...  1.38  2020      0.00       0.00
WSON33  0.14  0.61  32.18               3.88  ...  0.91  2020      4.19       8.07
YDUQ3   0.10  1.05  10.60               0.78  ...  1.86  2020      6.87       7.65

[165 rows x 9 columns]

In [48]:
df_consolidado = df_oceans.join(df_status).copy()
df_consolidado.to_csv('dados_oceans_status.csv', encoding='utf-8', index=False)
df_consolidado

         ECP  beta    VPA  ...    ROIC  lucros_5anos  liq_media_diaria
tick                       ...
AALR3   0.56  0.77  10.96  ...    4,36           NaN      9.190.647,37
ABEV3   0.22  0.62   4.58  ...   19,35         -0,28    395.449.207,87
ALPA4   0.82  0.97   4.87  ...    6,00         -1,97     59.103.410,47
ALSO3   0.00  1.19  28.67  ...    3,72        -27,08     70.559.096,27
ALUP11  0.10  0.55  25.73  ...   10,14         16,91     18.324.520,97
...      ...   ...    ...  ...     ...           ...               ...
VVAR3   0.84  1.56   0.49  ...  -24,20           NaN  1.387.518.919,03
WEGE3   0.35  0.87   4.71  ...   14,47         11,15    214.665.372,23
WIZS3   0.00  0.86   1.55  ...   92,92         21,33     11.146.933,30
WSON33  0.14  0.61  32.18  ...    4,04          4,05      1.756.442,03
YDUQ3   0.10  1.05  10.60  ...   12,43         12,26    128.947.298,83

[165 rows x 25 columns]